### ISSUE TITLE
keepalived_vip is not set

### ISSUE THREAD

**Issue by felipechaulet** [raspbernetes/k8s-cluster-installation#80]
Following the instructions from the installation guide, after running the command below:
**env ANSIBLE_CONFIG=ansible/ansible.cfg ansible-playbook \
    -i ansible/inventory \
    ansible/playbooks/all.yml**

I get this error:
`
TASK [validate variable : keepalived_vip] *******************************************************************************************************************************************************************`
`Sunday 06 December 2020  22:50:26 +0100 (0:00:00.131)       0:03:45.212 ******* `
`[WARNING]: The value '' is not a valid IP address or network, passing this value to ipaddr filter might result in breaking change in future.`
`fatal: [rpi-m01]: FAILED! => changed=false `
`  assertion: keepalived_vip | ipaddr`
`  evaluated_to: false`
`  msg:`
`  - Variable 'keepalived_vip' should be a valid ip address`
`  - 'Type is: AnsibleUnicode'`
`  - 'Value is: '`

At the moment, I have only one master node.

**Comment by crutonjohn** [comment]
The line in question is here: https://github.com/raspbernetes/k8s-cluster-installation/blob/271820f7b10b87094863c1c3461a56219deb4cea/ansible/roles/keepalived/tasks/pre_checks.yml#L12

While it isn't required to have a keepalived VIP when running the control plane components on a single master, our playbook sets up keepalived and haproxy for you on any nodes that are `masters`. Please reference the example group_vars settings here: https://github.com/raspbernetes/k8s-cluster-installation/tree/271820f7b10b87094863c1c3461a56219deb4cea/ansible/example/group_vars

From what it looks like, you've simply just not set a value for the `keepalived_vip` variable. If you need help getting the playbook set up, which vars to set, etc. feel free to join us on our discord: https://discord.com/invite/Yv2gzFy

**Comment by felipechaulet** [comment]
Thanks for the response @crutonjohn.

If it isn't required, is there a scenario where I don't set this value?
Also, is there any plan to update the documentation to include that this variable should be changed?
I have been following [this page](https://raspbernetes.github.io/docs/installation) and there's nothing mentioning this variable.

As there's a link to a page with advanced configuration options, that page is empty: https://raspbernetes.github.io/docs/advanced_installation/

**Comment by crutonjohn** [comment]
My apologies, perhaps I misspoke. 

It's absolutely possible to stand up a single-master cluster using the included playbook(s). In order to support varying different cluster designs, our playbooks treat all masters in the same way:
1. install/configure keepalived
2. install/configure haproxy
3. set up the control plane

By operating in the framework that all masters should receive the same set of configurations we allow for users to bring any number of master nodes to their cluster, be it one or be it nine. Such is the benefit of installing the HAproxy and keepalived components on all masters.

If you do not wish to install the keepalived and haproxy components to your master node, you can do so by omitting the `keepalived` and `haproxy` roles, and supplementing that with proper setting of the `cluster_control_plane_endpoint` variable at whichever level makes the most sense for your use-case. You can find that variable here: https://github.com/raspbernetes/k8s-cluster-installation/blob/80c7e1268cdbec7ee65b786c821bdd863c63e4c8/ansible/roles/cluster/defaults/main.yml#L5

I'm not sure if there are other considerations to be made in regards to the rest of the playbooks/variables, but perhaps @xUnholy or @RobReus can chime in.

**Comment by xunholy** [comment]
Thanks for raising this issue @felipechaulet, just to clarify your setup, how many master nodes will you have in your desired cluster?

The documentation does need some uplifting, I wrote a blog post recently that is more updated and can be found here https://itnext.io/automated-ha-kubernetes-deployment-on-raspberry-pis-408f38cd836c

If you're setting up a single master node instance we'll see what can be tweaked to accommodate, it should work but that being said I haven't run a single master node cluster to test it in quite a while as I do all my testing with HA masters these days.

**Comment by felipechaulet** [comment]
Hi,

at the moment, I am starting my "cluster" with only one node (a master, obviously). I have ordered a few more RPIs, but I would like to get the cluster started right away.

@xUnholy, thanks for that link. Following that I managed to move a bit forward into the deployment.
Now I am having a different error, related to calico.
fatal: [rpi-m01]: FAILED! => changed=true 
  cmd:
  - kubectl
  - apply
  - -f
  - https://docs.projectcalico.org/manifests/calico.yaml
  delta: '0:01:06.298278'
  end: '2020-12-07 09:54:43.449962'
  msg: non-zero return code
  rc: 1
  start: '2020-12-07 09:53:37.151684'
  stderr: The connection to the server localhost:8080 was refused - did you specify the right host or port?
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted

I understand this is a different issue and it might not even be a code issue, but perhaps I am not getting my head around the documentation.

**Comment by xunholy** [comment]
That is great you've managed to progress, to be able to debug faster would you be okay to join the discord channel in the org description? We'll be able to troubleshoot and discuss a little more smoothly and we can place the results that helped solved it back here for the community as we capture them.

**Comment by felipechaulet** [comment]
Following the link sent by @xUnholy I managed to deploy all the playbooks with no problem.

Note: I was using a RPI 3 with 1GB of ram as the master node and that's not enough memory to run all the k8s services.
I then replaced my master node with a RPI 4 2GB model (with the RPI 3 as worker node) and it worked just fine.
